# Generated by Django 3.1.1 on 2021-10-16 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appoint', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='prescription',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='appointment',
            name='special_note',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='appointment',
            name='symptoms',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='appointment',
            name='test_report',
            field=models.FileField(blank=True, null=True, upload_to='test_report/'),
        ),
    ]
